export const CONTRACT_ADDRESS = "0xc9E098e62c14C8DC015f238c226ea581Fa5C4425" as const;

export const FAIRPAY_ABI = [
  { inputs: [], name: "ClientFreelancerSame", type: "error" },
  { inputs: [], name: "DisputeNotResponded", type: "error" },
  { inputs: [], name: "DisputePeriodNotElapsed", type: "error" },
  { inputs: [], name: "EmptyWorkLink", type: "error" },
  { inputs: [], name: "EscrowNotFound", type: "error" },
  { inputs: [], name: "FreelancerAlreadyResponded", type: "error" },
  { inputs: [], name: "OnlyClient", type: "error" },
  { inputs: [], name: "OnlyFreelancer", type: "error" },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  { inputs: [], name: "ReviewPeriodNotElapsed", type: "error" },
  { inputs: [], name: "TransferFailed", type: "error" },
  {
    inputs: [
      { internalType: "enum State", name: "expected", type: "uint8" },
      { internalType: "enum State", name: "actual", type: "uint8" },
    ],
    name: "UnexpectedState",
    type: "error",
  },
  { inputs: [], name: "WorkDeadlineElapsed", type: "error" },
  { inputs: [], name: "WorkDeadlineNotElapsed", type: "error" },
  { inputs: [], name: "ZeroAddress", type: "error" },
  { inputs: [], name: "ZeroDeposit", type: "error" },
  { inputs: [], name: "ZeroPeriod", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "escrowId", type: "uint256" },
      { indexed: true, internalType: "address", name: "client", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "Approved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "escrowId", type: "uint256" },
      { indexed: true, internalType: "address", name: "client", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "Deposited",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "escrowId", type: "uint256" },
      { indexed: true, internalType: "address", name: "client", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "DisputeApproved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "escrowId", type: "uint256" },
      { indexed: true, internalType: "address", name: "freelancer", type: "address" },
      { indexed: false, internalType: "string", name: "proofLink", type: "string" },
    ],
    name: "DisputeProofSubmitted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "escrowId", type: "uint256" },
      { indexed: true, internalType: "address", name: "client", type: "address" },
      { indexed: false, internalType: "uint256", name: "disputeDeadline", type: "uint256" },
      { indexed: false, internalType: "string", name: "reason", type: "string" },
    ],
    name: "DisputeRaised",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "escrowId", type: "uint256" },
      { indexed: true, internalType: "address", name: "caller", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "DisputeTimeoutRefunded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "escrowId", type: "uint256" },
      { indexed: true, internalType: "address", name: "caller", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "DisputeTimeoutReleased",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "escrowId", type: "uint256" },
      { indexed: true, internalType: "address", name: "client", type: "address" },
    ],
    name: "DisputeWithdrawn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "escrowId", type: "uint256" },
      { indexed: true, internalType: "address", name: "client", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "EscrowCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "escrowId", type: "uint256" },
      { indexed: true, internalType: "address", name: "client", type: "address" },
      { indexed: true, internalType: "address", name: "freelancer", type: "address" },
    ],
    name: "EscrowCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "escrowId", type: "uint256" },
      { indexed: true, internalType: "address", name: "freelancer", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "RefundAccepted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "escrowId", type: "uint256" },
      { indexed: true, internalType: "address", name: "caller", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "ReviewTimeoutClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "escrowId", type: "uint256" },
      { indexed: true, internalType: "address", name: "freelancer", type: "address" },
      { indexed: false, internalType: "string", name: "workLink", type: "string" },
    ],
    name: "WorkSubmitted",
    type: "event",
  },
  {
    inputs: [{ internalType: "uint256", name: "escrowId", type: "uint256" }],
    name: "acceptRefund",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "escrowId", type: "uint256" }],
    name: "approve",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "escrowId", type: "uint256" }],
    name: "approveAfterDispute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "escrowId", type: "uint256" }],
    name: "cancelEscrow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "escrowId", type: "uint256" }],
    name: "claimAfterDisputeTimeout",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "escrowId", type: "uint256" }],
    name: "claimAfterReviewTimeout",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_freelancer", type: "address" },
      { internalType: "uint256", name: "_reviewPeriod", type: "uint256" },
      { internalType: "uint256", name: "_disputePeriod", type: "uint256" },
      { internalType: "uint256", name: "_workDuration", type: "uint256" },
    ],
    name: "createEscrow",
    outputs: [{ internalType: "uint256", name: "escrowId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "escrowId", type: "uint256" }],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "escrowId", type: "uint256" },
      { internalType: "string", name: "_reason", type: "string" },
    ],
    name: "dispute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "escrowCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "escrowId", type: "uint256" }],
    name: "getEscrow",
    outputs: [
      {
        components: [
          { internalType: "address", name: "client", type: "address" },
          { internalType: "address", name: "freelancer", type: "address" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "enum State", name: "state", type: "uint8" },
          { internalType: "string", name: "workLink", type: "string" },
          { internalType: "uint256", name: "submissionTimestamp", type: "uint256" },
          { internalType: "uint256", name: "reviewPeriod", type: "uint256" },
          { internalType: "uint256", name: "disputePeriod", type: "uint256" },
          { internalType: "uint256", name: "workDuration", type: "uint256" },
          { internalType: "uint256", name: "workDeadline", type: "uint256" },
          { internalType: "uint256", name: "disputeDeadline", type: "uint256" },
          { internalType: "bool", name: "disputeResponded", type: "bool" },
          { internalType: "string", name: "disputeReason", type: "string" },
          { internalType: "string", name: "disputeProof", type: "string" },
        ],
        internalType: "struct Escrow",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "escrowId", type: "uint256" }],
    name: "isDisputeTimeoutReached",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "escrowId", type: "uint256" }],
    name: "isReviewTimeoutReached",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "escrowId", type: "uint256" }],
    name: "isWorkDeadlineElapsed",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "escrowId", type: "uint256" }],
    name: "reviewDeadline",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "escrowId", type: "uint256" },
      { internalType: "string", name: "_proofLink", type: "string" },
    ],
    name: "submitDisputeProof",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "escrowId", type: "uint256" },
      { internalType: "string", name: "_workLink", type: "string" },
    ],
    name: "submitWork",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "escrowId", type: "uint256" }],
    name: "withdrawDispute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

// State enum mapping
export const STATE_LABELS: Record<number, string> = {
  0: "Created",
  1: "Funded",
  2: "Under Review",
  3: "Disputed",
  4: "Released",
};

export const STATE_COLORS: Record<number, string> = {
  0: "bg-zinc-100 text-zinc-700",
  1: "bg-blue-100 text-blue-700",
  2: "bg-yellow-100 text-yellow-700",
  3: "bg-red-100 text-red-700",
  4: "bg-green-100 text-green-700",
};
